modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/potion-Enchantments/issues/new/choose"
[[mods]]
modId="potionenchantments"
version="${file.jarVersion}"
displayName="Potion Enchantments"
displayURL="https://www.curseforge.com/minecraft/mc-mods/potion-enchantments"
logoFile="example.png"
credits="Thanks for downloading this mod."
authors="Ultramega"
description="This mod adds Potion Enchantments."

[[dependencies.potionenchantments]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potionenchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"